car_app/urls.py
from django.urls import path

from car_app.views import car_list_view

app_name = "car_app"

urlpatterns = [
    path("list/", car_list_view, name="car-list"),
]

rental_app/urls.py
from django.urls import path

from rental_app.views import rental_list_view, create_rental_view

app_name = "rental_app"

urlpatterns = [
    path("list/", rental_list_view, name="rental-list"),
    path('create/', create_rental_view, name='create-rental'),
]

user_app/urls.py
from django.urls import path

from user_app.views import login_view, logout_view, signup_view

app_name = "user_app"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup_view, name="signup"),
]

templates/home/admin.html
{% extends "base/base.html" %}

{% block title %}CRM | Admin Home{% endblock %}

{% block content %}

    {% if user.first_name %}
      <h1>Welcome {{ user.first_name }}</h1>
    {% else %}
      <h1>Welcome admin</h1>
    {% endif %}

    <a href="{% url 'user_app:logout' %}">Logout</a>

    <a href="{% url 'car_app:car-list' %}">Cars List</a>
    <a href="{% url 'rental_app:rental-list' %}">Rentals List</a>

{% endblock %}

templates/home/anonymous.html
{% extends "base/base.html" %}

{% block title %}CRM | Home{% endblock %}

{% block content %}

    <h1>Welcome to the Home page!</h1>
    <p>This is the home page of CRM.</p>
    <a href="{% url 'user_app:login' %}">Login</a>
    <a href="{% url 'user_app:signup' %}">SignUp</a>

    <a href="{% url 'user_app:login' %}?next={% url 'car_app:car-list' %}">Cars List</a>

{% endblock %}

templates/home/authenticated.html
{% extends "base/base.html" %}

{% block title %}CRM | User Home{% endblock %}

{% block content %}

    {% if user.first_name %}
      <h1>Welcome {{ user.first_name }}</h1>
    {% else %}
      <h1>Welcome</h1>
    {% endif %}

    <a href="{% url 'user_app:logout' %}">Logout</a>

{% endblock %}

templates/home/staff.html
{% extends "base/base.html" %}

{% block title %}CRM | Staff Home{% endblock %}

{% block content %}
    {% if user.first_name %}
      <h1>Welcome {{ user.first_name }}</h1>
    {% else %}
      <h1>Welcome</h1>
    {% endif %}

    <a href="{% url 'user_app:logout' %}">Logout</a>

    <a href="{% url 'car_app:car-list' %}">Cars List</a>
    <a href="{% url 'rental_app:create-rental' %}">Add Rental</a>
    <a href="{% url 'rental_app:rental-list' %}">Rentals List</a>

{% endblock %}